name: nutriary_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.1.0
  google_fonts: ^5.1.0
  infinite_scroll_pagination: ^4.0.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  dropdown_search: ^5.0.6
  intl: ^0.19.0
  calendar_date_picker2: ^0.5.5
  table_calendar: ^3.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  hive_generator: ^2.0.1



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/images/
